### ISSUE TITLE
Improving repo organisation

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/TINC#10]
Luca, I'd like to attach to this repo the same organisation we've setup for mobster (for GitHub Pages etc.). Can we arrange this?

**Comment by luca-dex** [comment]
You mean the automatic generation of pages with pkgdown through the gh action? Yes we can do this

**Comment by caravagn** [comment]
Yes, that would be fantastic - in general it would be good to get the general template for that, so we know how to adapt each one of the packages to that particular organisation.
