### ISSUE TITLE
error message 'Avoid using `snvs` if you use `mutations' when running sample data

### ISSUE THREAD

**Issue by huangdcc** [caravagnalab/TINC#11]
Hi,

I have just installed TINC recently. When I tried to run the example data at this step: load_TINC_input(x = sampled_data$data, cna = sampled_data$cna)

I got the error message as:

Error in `CNAqc::init()`:
! Avoid using `snvs` if you use `mutations
Run `rlang::last_trace()` to see where the error occurred

---
Backtrace:
    ▆
 1. └─TINC::load_TINC_input(x = sampled_data$data, cna = sampled_data$cna)
 2.   └─CNAqc::init(snvs = as_tumour(x), cna = cna, 0.8)
---
Backtrace:
    ▆
 1. └─TINC::load_TINC_input(x = sampled_data$data, cna = sampled_data$cna)
 2.   └─CNAqc::init(snvs = as_tumour(x), cna = cna, 0.8)
 3.     └─cli::cli_abort("Avoid using `snvs` if you use `mutations")
 4.       └─rlang::abort(...)

I have reinstalled CNAqc with 'devtools::install_github("caravagnalab/CNAqc")', but the error still remains.

Thank you very much for your help.

**Comment by Militeee** [comment]
Hi,
I've tried again with the new version of TINC and CNAqc and we fixed the issue. If you still have the same problems after updating both, please reopen the issue and provide the versioning of the packages in your environment.

Cheers,
S.
