### ISSUE TITLE
load_VCF_Strelka does not specify separate() call

### ISSUE THREAD

**Issue by ronkesm** [caravagnalab/TINC#14]
Just a small bug report. 

If you use load_VCF_Strelka before loading the tidyr package, the function returns this error:

**Code**
`x=TINC::load_VCF_Strelka("Outputs/Resequenced/somatic.snvs.vcf.gz")`

**Output**
`Error in separate(., ID, into = c("chr", "from", "to", "ref", "alt"),  : 
  could not find function "separate"`

Loading tidyr with `library(tidyr)` beforehand solves the issue

**Comment by Militeee** [comment]
Hi @ronkesm kudos for catching it. Fixed, thank you for reporting the bug.
S.
